name: BUILD

on:
  watch:
    types: started
  push:
  schedule:
    - cron:  '1 */3 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos:  #@ 改这里
          - systemd-kcm
          - dida-bin
          - google-chrome
          - microsoft-edge-stable-bin
          - visual-studio-code-bin
          - yesplaymusic-electron
          - wps-office-cn
          - wps-office-mime-cn
          - wps-office-mui-zh-cn
          - nerd-fonts-sarasa-mono
          - tlpui
          - noto-fonts-lite
          - easyconnect

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - uses: ./build-aur-action
      with:
        repo-name: ${{ matrix.repos }}
    
    - uses: actions/upload-artifact@v2
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: "packages"
        artifacts: "./*/*.zst"
        token: ${{ secrets.GITHUB_TOKEN }}

  buildNonAUR:
    strategy:
      matrix:
        PKGBUILDs: [BBDown] #@ 改这里

      fail-fast: false
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Non-AUR packages
        id: makepkg
        uses: ./build-nonaur-action
        with:
          pkgdir: ${{ matrix.PKGBUILDs }}
          aurDeps: true
          
      - uses: actions/upload-artifact@v2
        with:
          path: ./*/*.pkg.tar.zst
          name: ${{ matrix.PKGBUILDs }}
      
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: ${{ steps.makepkg.outputs.pkgfile0 }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
  createDB:      
    runs-on: ubuntu-latest
    if: always()
    needs: [buildAUR, buildNonAUR]

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        id: download
      
      - uses: ./update-db-for-repo
        with:
          tag: packages
          
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "packages"
          artifacts: "./packages.*"
          token: ${{ secrets.GITHUB_TOKEN }}
